//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHomeIce;

/**
 * Helper class for marshaling/unmarshaling orderedShoppingList.
 **/
public final class orderedShoppingListHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, OrderedShoppingListRecord[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                ostr.writeValue(v[i0]);
            }
        }
    }

    public static OrderedShoppingListRecord[] read(com.zeroc.Ice.InputStream istr)
    {
        final OrderedShoppingListRecord[] v;
        final int len0 = istr.readAndCheckSeqSize(1);
        v = new OrderedShoppingListRecord[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            final int fi0 = i0;
            istr.readValue(value -> v[fi0] = value, OrderedShoppingListRecord.class);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<OrderedShoppingListRecord[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, OrderedShoppingListRecord[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            orderedShoppingListHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<OrderedShoppingListRecord[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            OrderedShoppingListRecord[] v;
            v = orderedShoppingListHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
