// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecutionService.proto

package dynamic.calls.Executors;

/**
 * Protobuf service {@code dynamic.calls.Executors.ExecutionService}
 */
public  abstract class ExecutionService
    implements com.google.protobuf.Service {
  protected ExecutionService() {}

  public interface Interface {
    /**
     * <code>rpc execute(.dynamic.calls.Executors.ExecutionRequest) returns (.dynamic.calls.Executors.ExecutionResponse);</code>
     */
    public abstract void execute(
        com.google.protobuf.RpcController controller,
        dynamic.calls.Executors.ExecutionRequest request,
        com.google.protobuf.RpcCallback<dynamic.calls.Executors.ExecutionResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new ExecutionService() {
      @java.lang.Override
      public  void execute(
          com.google.protobuf.RpcController controller,
          dynamic.calls.Executors.ExecutionRequest request,
          com.google.protobuf.RpcCallback<dynamic.calls.Executors.ExecutionResponse> done) {
        impl.execute(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.execute(controller, (dynamic.calls.Executors.ExecutionRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return dynamic.calls.Executors.ExecutionRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return dynamic.calls.Executors.ExecutionResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc execute(.dynamic.calls.Executors.ExecutionRequest) returns (.dynamic.calls.Executors.ExecutionResponse);</code>
   */
  public abstract void execute(
      com.google.protobuf.RpcController controller,
      dynamic.calls.Executors.ExecutionRequest request,
      com.google.protobuf.RpcCallback<dynamic.calls.Executors.ExecutionResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return dynamic.calls.Executors.ExecutionServiceOuterClass.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.execute(controller, (dynamic.calls.Executors.ExecutionRequest)request,
          com.google.protobuf.RpcUtil.<dynamic.calls.Executors.ExecutionResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return dynamic.calls.Executors.ExecutionRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return dynamic.calls.Executors.ExecutionResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends dynamic.calls.Executors.ExecutionService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void execute(
        com.google.protobuf.RpcController controller,
        dynamic.calls.Executors.ExecutionRequest request,
        com.google.protobuf.RpcCallback<dynamic.calls.Executors.ExecutionResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        dynamic.calls.Executors.ExecutionResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          dynamic.calls.Executors.ExecutionResponse.class,
          dynamic.calls.Executors.ExecutionResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public dynamic.calls.Executors.ExecutionResponse execute(
        com.google.protobuf.RpcController controller,
        dynamic.calls.Executors.ExecutionRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public dynamic.calls.Executors.ExecutionResponse execute(
        com.google.protobuf.RpcController controller,
        dynamic.calls.Executors.ExecutionRequest request)
        throws com.google.protobuf.ServiceException {
      return (dynamic.calls.Executors.ExecutionResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        dynamic.calls.Executors.ExecutionResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:dynamic.calls.Executors.ExecutionService)
}

