// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecutionService.proto

package dynamic.calls.Executors;

public interface ExecutionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dynamic.calls.Executors.ExecutionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string error = 1;</code>
   */
  java.lang.String getError();
  /**
   * <code>string error = 1;</code>
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <code>string data = 2;</code>
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
