// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecutionService.proto

package dynamiccalls.Executors;

public interface ExecutionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dynamiccalls.Executors.ExecutionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string error = 1;</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 1;</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <code>string data = 2;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
