//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

/** @hidden */
public class _CO2LevelSensorPrxI extends com.zeroc.Ice._ObjectPrxI implements CO2LevelSensorPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
