//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public interface FridgeWithIceCubeMakerPrx extends FridgePrx
{
    default int getIceCubesMakerCapacity()
    {
        return getIceCubesMakerCapacity(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int getIceCubesMakerCapacity(java.util.Map<String, String> context)
    {
        return _iceI_getIceCubesMakerCapacityAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getIceCubesMakerCapacityAsync()
    {
        return _iceI_getIceCubesMakerCapacityAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getIceCubesMakerCapacityAsync(java.util.Map<String, String> context)
    {
        return _iceI_getIceCubesMakerCapacityAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_getIceCubesMakerCapacityAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getIceCubesMakerCapacity", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default int getIceCubes(int count)
        throws InStandbyModeError,
               NotEnoughIceCubesError
    {
        return getIceCubes(count, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int getIceCubes(int count, java.util.Map<String, String> context)
        throws InStandbyModeError,
               NotEnoughIceCubesError
    {
        try
        {
            return _iceI_getIceCubesAsync(count, context, true).waitForResponseOrUserEx();
        }
        catch(InStandbyModeError ex)
        {
            throw ex;
        }
        catch(NotEnoughIceCubesError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getIceCubesAsync(int count)
    {
        return _iceI_getIceCubesAsync(count, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getIceCubesAsync(int count, java.util.Map<String, String> context)
    {
        return _iceI_getIceCubesAsync(count, context, false);
    }

    /**
     * @hidden
     * @param iceP_count -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_getIceCubesAsync(int iceP_count, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getIceCubes", null, sync, _iceE_getIceCubes);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_count);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getIceCubes =
    {
        InStandbyModeError.class,
        NotEnoughIceCubesError.class
    };

    default int getIceCubesCount()
        throws InStandbyModeError
    {
        return getIceCubesCount(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int getIceCubesCount(java.util.Map<String, String> context)
        throws InStandbyModeError
    {
        try
        {
            return _iceI_getIceCubesCountAsync(context, true).waitForResponseOrUserEx();
        }
        catch(InStandbyModeError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getIceCubesCountAsync()
    {
        return _iceI_getIceCubesCountAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getIceCubesCountAsync(java.util.Map<String, String> context)
    {
        return _iceI_getIceCubesCountAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_getIceCubesCountAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getIceCubesCount", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_getIceCubesCount);
        f.invoke(true, context, null, null, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getIceCubesCount =
    {
        InStandbyModeError.class
    };

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static FridgeWithIceCubeMakerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), FridgeWithIceCubeMakerPrx.class, _FridgeWithIceCubeMakerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static FridgeWithIceCubeMakerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), FridgeWithIceCubeMakerPrx.class, _FridgeWithIceCubeMakerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static FridgeWithIceCubeMakerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), FridgeWithIceCubeMakerPrx.class, _FridgeWithIceCubeMakerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static FridgeWithIceCubeMakerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), FridgeWithIceCubeMakerPrx.class, _FridgeWithIceCubeMakerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static FridgeWithIceCubeMakerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, FridgeWithIceCubeMakerPrx.class, _FridgeWithIceCubeMakerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static FridgeWithIceCubeMakerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, FridgeWithIceCubeMakerPrx.class, _FridgeWithIceCubeMakerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (FridgeWithIceCubeMakerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_adapterId(String newAdapterId)
    {
        return (FridgeWithIceCubeMakerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (FridgeWithIceCubeMakerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (FridgeWithIceCubeMakerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_invocationTimeout(int newTimeout)
    {
        return (FridgeWithIceCubeMakerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_connectionCached(boolean newCache)
    {
        return (FridgeWithIceCubeMakerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (FridgeWithIceCubeMakerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_secure(boolean b)
    {
        return (FridgeWithIceCubeMakerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (FridgeWithIceCubeMakerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_preferSecure(boolean b)
    {
        return (FridgeWithIceCubeMakerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (FridgeWithIceCubeMakerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (FridgeWithIceCubeMakerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_collocationOptimized(boolean b)
    {
        return (FridgeWithIceCubeMakerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_twoway()
    {
        return (FridgeWithIceCubeMakerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_oneway()
    {
        return (FridgeWithIceCubeMakerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_batchOneway()
    {
        return (FridgeWithIceCubeMakerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_datagram()
    {
        return (FridgeWithIceCubeMakerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_batchDatagram()
    {
        return (FridgeWithIceCubeMakerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_compress(boolean co)
    {
        return (FridgeWithIceCubeMakerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_timeout(int t)
    {
        return (FridgeWithIceCubeMakerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_connectionId(String connectionId)
    {
        return (FridgeWithIceCubeMakerPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default FridgeWithIceCubeMakerPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (FridgeWithIceCubeMakerPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SmartHome::FridgeWithIceCubeMaker";
    }
}
