//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public class NotEnoughIceCubesError extends com.zeroc.Ice.UserException
{
    public NotEnoughIceCubesError()
    {
    }

    public NotEnoughIceCubesError(Throwable cause)
    {
        super(cause);
    }

    public String ice_id()
    {
        return "::SmartHome::NotEnoughIceCubesError";
    }

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::SmartHome::NotEnoughIceCubesError", -1, true);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 1882048783L;
}
