//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public class OrderedShoppingListRecord extends com.zeroc.Ice.Value
{
    public OrderedShoppingListRecord()
    {
    }

    public OrderedShoppingListRecord(int id, ShoppingListRecord shoppingListRecord)
    {
        this.id = id;
        this.shoppingListRecord = shoppingListRecord;
    }

    public int id;

    public ShoppingListRecord shoppingListRecord;

    public OrderedShoppingListRecord clone()
    {
        return (OrderedShoppingListRecord)super.clone();
    }

    public static String ice_staticId()
    {
        return "::SmartHome::OrderedShoppingListRecord";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -670769723L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeInt(id);
        ostr_.writeValue(shoppingListRecord);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        id = istr_.readInt();
        istr_.readValue(v -> shoppingListRecord = v, ShoppingListRecord.class);
        istr_.endSlice();
    }
}
