//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public class OrderedShoppingListRecord extends ShoppingListRecord
{
    public OrderedShoppingListRecord()
    {
        super();
    }

    public OrderedShoppingListRecord(String name, int quantity, Unit unit, int id)
    {
        super(name, quantity, unit);
        this.id = id;
    }

    public int id;

    public OrderedShoppingListRecord clone()
    {
        return (OrderedShoppingListRecord)super.clone();
    }

    public static String ice_staticId()
    {
        return "::SmartHome::OrderedShoppingListRecord";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = 801472788L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, false);
        ostr_.writeInt(id);
        ostr_.endSlice();
        super._iceWriteImpl(ostr_);
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        id = istr_.readInt();
        istr_.endSlice();
        super._iceReadImpl(istr_);
    }
}
