//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public class ShoppingListRecord extends com.zeroc.Ice.Value
{
    public ShoppingListRecord()
    {
        this.name = "";
        this.unit = Unit.Unspecified;
    }

    public ShoppingListRecord(String name, int quantity, Unit unit)
    {
        this.name = name;
        this.quantity = quantity;
        this.unit = unit;
    }

    public String name;

    public int quantity;

    public Unit unit;

    public ShoppingListRecord clone()
    {
        return (ShoppingListRecord)super.clone();
    }

    public static String ice_staticId()
    {
        return "::SmartHome::ShoppingListRecord";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -956096223L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeString(name);
        ostr_.writeInt(quantity);
        Unit.ice_write(ostr_, unit);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        name = istr_.readString();
        quantity = istr_.readInt();
        unit = Unit.ice_read(istr_);
        istr_.endSlice();
    }
}
